config/routes.rb
SwissMtg::Application.routes.draw do

  devise_for :users

  patch '/tournaments/:id/add_player_list', :to => 'tournaments#add_player_list'

  patch '/tournaments/:id/update_results', :to => 'tournaments#update_results'

  post '/tournaments/:id/generate_round', :to => 'tournaments#generate_round'

  get '/tournaments/:id/remove_player', :to => 'tournaments#remove_player'

  post '/tournaments/:id/re_generate_round', :to => 'tournaments#re_generate_round'

  post '/tournaments/:id/end_prelims', :to => 'tournaments#end_prelims'

  resources :players

  resources :users

  resources :tournaments

  root 'tournaments#index'

end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  has_many :matches
  has_many :player_tournaments
  has_many :players, through: :player_tournaments
  has_many :user_tournaments
  has_many :users, through: :user_tournaments

  def generate
    self.current_round ||= 0
    self.current_round += 1
    self.save
    assess_rounds if current_round == 1
    create_matches
    self.save
  end

  def re_generate
    self.matches.sort_by{|m| m.id }.last.player_1.update(bye_round: nil) 
    self.matches.where(round: self.current_round).destroy_all
    create_matches
  end

  def end_tournament
    self.finished = true
    self.current_round += 1
    self.save
  end

  def round_started
    self.matches.where(round: current_round).where("game_1 IS NOT null").length > 0 
  end

  def assess_rounds
    number_of_players = self.players.all.size
    case number_of_players
      when 0...8
        #Throw Error; Is this deprecated due to dependencies to start tournament?
      when 8
        self.number_of_rounds = 3
      when 9...17
        self.number_of_rounds = 4
      when 17...33
        self.number_of_rounds = 5
      when 33...65
        self.number_of_rounds = 6
      when 65...129
        self.number_of_rounds = 7
      when 129...227
        self.number_of_rounds = 8
      when 227...410
        self.number_of_rounds = 9
      else 
        self.number_of_rounds = 10
    end
    number_of_rounds
  end

  def create_matches
    if current_round == 1
      player_list = self.player_tournaments.to_a.shuffle
      bye_player = player_list.pop if player_list.size.odd?
    elsif self.player_tournaments.size.odd?
      player_list = already_bye?
      bye_player = player_list.pop
      player_list = validate_players(player_list)
    else
      player_list = validate_players(self.order_players)
    end

    while player_list.size > 0
      self.matches.create(:player_1 => player_list.shift, :player_2 => player_list.shift, :round => self.current_round)
    end

    if bye_player
      self.matches.create(player_1_id: bye_player.id, round: self.current_round)
      bye_player.update(bye_round: self.current_round)
    end
  end

  def validate_players(player_list)
    valid_list = false
    reversed = true
    rep = []
    while !valid_list
      matched = []
      valid_list = true
      reversed = !reversed
      while player_list.size > 0
        if !already_played?(player_list[0], player_list[1])
          valid_list = false if player_list[1] == nil
          matched = matched + player_list.slice!(0, 2)
          player_list = rep + player_list
          rep = []
        else
          rep << player_list.slice!(1)
        end
        matched.compact!
      end
      !valid_list ? player_list = matched.reverse! : player_list = matched
    end
    reversed ? player_list.reverse : player_list
  end

  def already_played?(player_tournament_1, player_tournament_2)
    self.matches.each do |match|
      x = 0
      x += 1 if match.player_1_id == player_tournament_1.id
      x += 1 if match.player_2_id == player_tournament_1.id
      x += 1 if player_tournament_2 && (match.player_1_id == player_tournament_2.id)
      x += 1 if player_tournament_2 && (match.player_2_id == player_tournament_2.id)
      return true if (x == 2)
    end
    false
  end


  def already_bye?
    players = self.order_players.to_a
    if players[-1].had_bye
      next_bye = players.reverse[0..-2].detect { |player| !player.had_bye }
      players.delete(next_bye)
      players << next_bye
    else
      players
    end
  end

  def order_players
    # binding.pry
    self.player_tournaments.includes(:finished_matches_as_1, :finished_matches_as_2).sort_by{|p| [-p.match_points, -p.opponents_match_avg, -p.game_win_percent, -p.opponents_game_avg, p.id] }
  end

  def find_or_create_player(name)
    player = Player.find_or_create_by(:name => name.downcase.titleize)
    self.player_tournaments.find_or_create_by(player_id: player.id)
  end

  def end_message
    #self.format == "Swiss Pairings, Without Finals" ? "End Tournament" : "Generate Finals"
    "End Tournament"
  end

  def round_complete
    completed = self.matches.select {|m| m.game_1 && m.game_1 >= 0 }
    completed.size == self.matches.size
  end

  def finals?
    current_round > number_of_rounds
  end

  def generate_finals
    # if number == 4
    #   pair player one with player four
    #   pair player two with player three
    # elsif number == 8 
  end

end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [:show, :edit, :update, :destroy, :generate_round, :re_generate_round, :add_players, :remove_player, :update_results, :end_prelims, :add_player_list]

  skip_before_filter :authenticate_user!, only: [:index, :show]

  # GET /tournaments
  # GET /tournaments.json
  def index
    @tournaments = Tournament.all
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
  end

  # GET /tournaments/new
  def new
    @tournament = Tournament.new
  end

  # GET /tournaments/1/edit
  def edit
    if current_user && current_user.id == @tournament.users[0].id
      render :edit
    else
      redirect_to @tournament, notice: 'You do not have the proper permissions, you terrorist.'
    end
  end

  def add_player_list
    if current_user && current_user.id == @tournament.users[0].id
      names = tournament_params["name"].split(',').map(&:strip)
      names.each do |name|
        @tournament.find_or_create_player(name)
      end
      redirect_to @tournament
    else
      redirect_to @tournament, notice: 'You do not have the proper permissions, you terrorist.'
    end
  end

  def remove_player
    if current_user && current_user.id == @tournament.users[0].id
      pt = @tournament.player_tournaments.find(params[:p_id])
      pt.player.destroy if pt.player.player_tournaments.size == 1
      pt.destroy
      @tournament.select_array
      redirect_to @tournament, notice: 'Player removed'
    else
      redirect_to @tournament, notice: 'You do not have the proper permissions, you terrorist.'
    end
  end


  # POST /tournaments
  # POST /tournaments.json
  def create
    @tournament = Tournament.new(tournament_params)
    
    respond_to do |format|
      if @tournament.save
        UserTournament.create(tournament_id: @tournament.id, user_id: current_user.id)
        format.html { redirect_to @tournament, notice: 'Tournament was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tournament }
      else
        format.html { render action: 'new' }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_results
    match = Match.find(match_params[:match_id])
    match.update(game_1: match_params[:game_1], game_2: match_params[:game_2], game_3: match_params[:game_3])
    redirect_to @tournament
  end

  # PATCH/PUT /tournaments/1
  # PATCH/PUT /tournaments/1.json
  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_url }
      format.json { head :no_content }
    end
  end

  def generate_round
    if @tournament.round_complete
      redirect_to @tournament, notice: "Round #{@tournament.current_round} Matches Generated"
      @tournament.update(number_of_rounds: params[:tournament][:number_of_rounds]) if !@tournament.number_of_rounds
      @tournament.generate 
    else
      redirect_to @tournament, notice: "New round pairings cannot be generated until the current round has been completed"
    end
  end

  def re_generate_round
    redirect_to @tournament, notice: "Round #{@tournament.current_round} Matches Re-Generated"
    @tournament.re_generate
  end

  def end_prelims
    redirect_to @tournament
    @tournament.end_tournament
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tournament_params
      params.require(:tournament).permit(:name, :format, :location, :date, :details)
    end

    def match_params
      params.require(:match).permit(:match_id, :game_1, :game_2, :game_3)
    end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.erb
<%= form_for(@tournament) do |f| %>
  <% if @tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
      <% @tournament.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, required: true%><br><br>
    <!-- <%#= f.label :format %><br> -->
    <!-- <%#= f.select(:format, options_for_select([["Swiss Pairings, With Finals", "Swiss Pairings, With Finals"], ["Swiss Pairings, Without Finals", "Swiss Pairings, Without Finals"]])) %><br><br> -->
    <%= f.label :location %><br>
    <%= f.text_field :location %><br><br>
    <%= f.label :date %><br>
    <%= f.date_select :date %><br><br>
    <%= f.label :details %><br>
    <%= f.text_area :details, cols: 50, rows: 10 %><br><br>
  </div>
  <div class="actions">
    <%= f.submit "Submit",class: "btn btn-danger btn-md"%>
  </div>
<% end %>

app/views/tournaments/_player_list.html.erb
<ol id="player_sidebar">
<% @tournament.order_players.each do |p| %>
  <li>
    <strong><%= p.player.name %></strong>
    <% if @tournament.current_round != nil %>
      <br>
      <%= p.match_points %> points | <%= p.record %> | <%= (p.opponents_match_avg * 100).round(2) %>%
    <% else %>
      <%= link_to 'x', :controller => "tournaments", action: "remove_player", :p_id => p.id %>
    <% end %>
  </li>
<% end %>

    
</ol>

app/views/tournaments/_public_round.html.erb
<ul class="nav nav-tabs" id="roundtabs">
  <% @tournament.number_of_rounds.times do |n| %>
    <li><a href="#round-<%=
 n + 1 %>" data-toggle="tab"
      <% if @tournament.current_round < n + 1 %>
        style="color: grey;"
      <% end %>
      >Round <%= n + 1 %></a></li>
  <% end %>
</ul>


<div class="tab-content">
  <% @tournament.number_of_rounds.times do |round_n| %>
  <div class="tab-pane" id="round-<%= round_n + 1 %>">
    <% if (round_n + 1) > @tournament.current_round %>
      <h3>Round Not Started</h3>
    <% else %>
      <table class="table formatted_table">
        <thead>
          <tr>
            <th class="table_number">Table</th>
            <th class="centerizer">Player 1</th>
            <th class="results-col">Match Results</th>
            <th class="centerizer">Player 2</th>
          </tr>
        </thead>
        <br>
        <% i = 1 %>
         <% @tournament.matches.select{ |m| m.round == round_n + 1 }.sort_by{ |m| m.id}.each do |match| %>
          <tr style="<%= "background-color: grey;" if match.finished? %>">
            <td><%= i %></td>
            <% i += 1 %>
            <td><%= match.player_1.player.name %></td>
            <% if match.player_2 != nil %>
              <td>
                
                <% if match.game_1 && match.game_1 == match.player_1_id %>
                  P1
                <% elsif match.game_1 && match.game_1 == match.player_2_id %>
                  P2
                <% elsif match.game_1 == 0 %>
                  D
                <% else %>
                  -
                <% end %>

                <% if match.game_2 && match.game_2 == match.player_1_id %>
                  P1
                <% elsif match.game_2 && match.game_2 == match.player_2_id %>
                  P2
                <% elsif match.game_2 == 0 %>
                  D
                <% else %>
                  -
                <% end %>

                <% if match.game_3 && match.game_3 == match.player_1_id %>
                  P1
                <% elsif match.game_3 && match.game_3 == match.player_2_id %>
                  P2
                <% elsif match.game_3 == 0 %>
                  D
                <% else %>
                  -
                <% end %>

              </td>
              <td><%= match.player_2.player.name %></td>
            <% else %>
              <td></td>
              <td>BYE</td>
            <% end %>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
  <% end %>
</div>

<script>
  $(function(){
    $('#roundtabs a[href="#round-<%= @tournament.current_round %>"]').tab('show');
  });
</script>

app/views/tournaments/_round.html.erb
<ul class="nav nav-tabs" id="roundtabs">
  <% @tournament.number_of_rounds.times do |n| %>
    <li><a href="#round-<%= n + 1 %>" data-toggle="tab"
      <% if @tournament.current_round < n + 1 %>
        style="color: grey;"
      <% end %>
      >Round <%= n + 1 %></a></li>
  <% end %>
</ul>


<div class="tab-content">
  <% @tournament.number_of_rounds.times do |round_n| %>
  <div class="tab-pane" id="round-<%= round_n + 1 %>">
    <% if (round_n + 1) > @tournament.current_round %>
      <h3>Round Not Started</h3>
    <% else %>
      <table class="table formatted_table">
        <thead>
          <tr>
            <th class="table_number">Table</th>
            <th class="centerizer">Player 1</th>
            <th class="results-col">Match Results</th>
            <th class="centerizer">Player 2</th>
            <!-- <th></th> -->
          </tr>
        </thead>
        <% i = 1 %>
        <% @tournament.matches.select{ |m| m.round == round_n + 1 }.sort_by{ |m| m.id}.each do |match| %>
          <tr style="<%= "background-color: grey;" if match.finished? %>">
            <td><%= i %></td>
            <% i += 1 %>
            <td><%= match.player_1.player.name %></td>
            <% if match.player_2 != nil %>
              <td>
                <%= form_for match, url: {action: "update_results"}, data: { id: match.id } do |f| %>
                  <%= f.select(:game_1, options_for_select([["-", "-"],["P1", match.player_1_id], ["P2", match.player_2_id], ["D", 0], ["NP", -1]], match.game_1), {}, class: 'result-input')%>
                  <%= f.select(:game_2, options_for_select([["-", "-"],["P1", match.player_1_id], ["P2", match.player_2_id], ["D", 0], ["NP", -1]], match.game_2), {}, class: 'result-input')%>
                  <%= f.select(:game_3, options_for_select([["-", "-"],["P1", match.player_1_id], ["P2", match.player_2_id], ["D", 0], ["NP", -1]], match.game_3), {}, class: 'result-input')%>
                  <%= f.hidden_field :match_id, :value => match.id %>
                <% end %>
              </td>
              <td><%= match.player_2.player.name %></td>
            <% else %>
              <td>
                <%= form_for(match, html: {:class => 'bye_form'}, url: {action: "update_results"}, data: { id: match.id })  do |f| %>
                  <%= f.hidden_field :game_1, :value => match.player_1_id %>
                  <%= f.hidden_field :game_2, :value => match.player_1_id %>
                  <%= f.hidden_field :match_id, :value => match.id %>
                <% end %>
                <button class="btn btn-danger btn-xs bye_button"> Confirm Bye </button>
              </td>

              <% if !@tournament.finished %>
                <td>BYE</td>
              <% end %>
            <% end %>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
  <% end %>
</div>

<script>
  $(function(){
    $('#roundtabs a[href="#round-<%= @tournament.current_round %>"]').tab('show');
  });
</script>

app/views/tournaments/edit.html.erb
<h1>Editing tournament</h1>

<%= render 'form' %>

<%= link_to 'Show', @tournament %> |
<%= link_to 'Back', tournaments_path %>

app/views/tournaments/index.html.erb
  <div class="row">
    <div class="col-md-12">
      <h1 class="titleything">Tournaments</h1>
            <% if current_user %>
             <h3><%= link_to 'New Tournament', new_tournament_path %></h3>
             <br> 
             <% else %>
             <h3> Please Login to Create a Tournament </h3>
            <% end %>



            <% @tournaments.sort_by {|tournament| -tournament.id }.each do |tournament| %>
              <h3> <%= link_to tournament.name, tournament %> </h3>
            <% end %>



    </div>
  </div>

app/views/tournaments/new.html.erb
<div style="text-align: center;">
<h1>New Tournament</h1>

<%= render 'form' %>

</div>

app/views/tournaments/show.html.erb
<h2><%= @tournament.name %></h2> 
<p >
  <!-- <strong>Format:</strong> -->
  <!-- <%#= @tournament.format if @tournament.format %> |  -->
  <strong>Date:</strong>
  <%= @tournament.date if @tournament.date %> | 
  <strong>Location:</strong>
  <%= @tournament.location if @tournament.location %> | 
  <strong>Details:</strong>
  <%= @tournament.details if @tournament.details %>
</p>


<!-- Example row of columns -->
<div class="row">
  <div class="col-md-12" >
    <% if @tournament.number_of_rounds && !@tournament.finished %>
    <h3> This Tournament Will Be <%= @tournament.number_of_rounds %> Rounds Long - Currently Round <%= @tournament.current_round %></h3>
    <% elsif @tournament.finished %>
    <h3> The Tournament is Finished. </h3>
    <% end %>
  </div>
</div>

<p id="notice" ><%= notice %></p>

<div id="buttonHouse">
  <% if current_user && current_user.id == @tournament.users[0].id%>
    <% if @tournament.players.size < 8 && !@tournament.finished %>
      <p>The tournament must have at least 8 players.</p>
    <% elsif !@tournament.round_started && @tournament.current_round && !@tournament.finished %>
      <p><%= button_to 'Re-Generate Round', {action: "re_generate_round"}, {class: 'btn btn-danger btn-md'} %> <em>(use if results from previous round have been updated)</em></p>
    <% elsif !@tournament.round_complete %>
      <p>The next round can be generated once all matches are resolved</p>
    <% elsif @tournament.current_round == @tournament.number_of_rounds && @tournament.current_round != nil && !@tournament.finished %>
      <p><%= button_to @tournament.end_message , {action: "end_prelims"}, {class: "btn btn-danger btn-md"} %></p>
    <% elsif !@tournament.finished %>
      <%= button_to "#{@tournament.current_round ? 'Generate Next Round' : 'Confirm Playerlist and Start Tournament'}", {action: "generate_round"}, {class: "btn btn-danger btn-md"} %>
    <% end %>
  <%end%>
</div>

<br>


<div class="col-md-4 player_list_overflow">
  <% if current_user && !@tournament.current_round && current_user.id == @tournament.users[0].id%>
    <%= form_for @tournament, :url => {:action => 'add_player_list'} do |f| %>
    <%= f.text_area :name, cols: 40, rows: 10, :value => "", placeholder: "Names" %>
    <br>
    <em> (comma separate names) </em>
    <br>
    <br>
    <%= f.submit "Add Player(s)" , {class: "btn btn-danger btn-md"} %>
    <br>
    <br>
    <% end %>
  <% end %>

  <% if @tournament.current_round != nil %>
  <h4 id="standings_style"> 
  <ol id="player_sidebar">
    <% @tournament.order_players.each do |p| %>
      <li>
        <strong><%= p.player.name %></strong>
        <% if @tournament.current_round != nil %>
          <br>
          <%= p.match_points %> points | <%= p.record %> | <%= (p.opponents_match_avg * 100).round(2) %>%
        <% else %>
          <%= link_to 'x', :controller => "tournaments", action: "remove_player", :p_id => p.id %>
        <% end %>
      </li>
    <% end %>
  </ol>
  <% end %>
</div>

<div class="col-md-8" id="pairing_sidebar" style="overflow-x: hidden;">
  <% if current_user && @tournament.current_round && !@tournament.finals? && current_user.id == @tournament.users[0].id && !@tournament.finished %>
    <%= render 'round' %>
  <% elsif @tournament.current_round %>
    <%= render 'public_round'%>
  <% else  %>
    <%= render 'player_list' %>
  <% end %>
</div>
    
<br>

<% if @tournament.current_round != nil %>
<script>$(function(){
  //get height for 2
  var barHeight = $('.nav-tabs').height();
  var bar2Height = $('.tab-pane').height();
  var col2Height = barHeight + bar2Height;
  //set height for 1
  col2Height > 350 ? $('#player_sidebar').height(col2Height) : $('#player_sidebar').height("350px");
});</script>
<% end %>